### ISSUE TITLE
Mi 6X there are problems (MIUI 11 9.9.26) 

### ISSUE THREAD

**Issue by ali39ali** [suat074/MA-XML-11-TURKISH#1]
Mi 6X cameras will not turn on. The interface is too tight. When you open the lock screen, the black screen goes on and off. When the phone is connected to the Internet, the display (the storage area of ​​the device is damaged) is displayed. When the battery level drops to 10%, the phone becomes unusable. These problems need to be corrected.

**Comment by ali39ali** [comment]
@suat074 @suatsari

**Comment by rabilgic** [comment]
Hocam ingiliççe kasmana gerek yok, derdini güzel ve çok değerli Türkçe`mizi kullanarak anlatabilirsin. Bahsedilen problemlerin çeviri sorunları ile herhangi bir ilgisi bulunmamakta, sorunlarını xiaomi.eu forumunun bug sekmesinde logcat sonuçlarını ekleyerek konu açabilirsin.

**Comment by ingbrzy** [comment]
not a translation issue
