### ISSUE TITLE
Mesajlar bölümünde çeviri eksikliği

### ISSUE THREAD

**Issue by cerhan82** [suat074/MA-XML-11-TURKISH#13]
Suat Bey, 
Mi6 11.0.2 ve Note 7 11.0.3 romlarda mesajlar bölümünde, mesajın içine girip silmek isteyince türkçe yazıyor ama mesajı açmadan mesajı silmek isteyince çıkan uyarı ingilizce kalmış (delete this conversation?). Kolay gelsin.

**Comment by suat074** [comment]
Bu sorun beta sürümünde düzeltildi. Yeni çıkacak olan stabil sürümlerde de düzelmiş olacaktır.
