### ISSUE TITLE
K20 pro bootloop

### ISSUE THREAD

**Issue by fatihimmgl** [suat074/MA-XML-11-TURKISH#14]
Stabil eu romda Türkçe dilinde yeniden başlatınca bootloop oluyor . Beta sürümünde böyle bir sorun yokken stabilde bu sorun var nasıl çözeriz?

**Comment by ingbrzy** [comment]
can not be solved without logcat

**Comment by Tmp341** [comment]
> 
> 
> can not be solved without logcat

@fatihmmgl Logcat olmadan düzeltilemez diyor.

@ingbrzy I've just translated what you've said.
