### ISSUE TITLE
Şarj sorunu 

### ISSUE THREAD

**Issue by byfunny** [suat074/MA-XML-11-TURKISH#15]
Guncellemeden sonra telefonum yeniden başlatmadan şarj olmuyor.ayrica yeniden başlat dedinde kapanıp kalıyor. Yeniden power tuşuna uzun süre basiyorum öyle açılıyor.acilsiktan yaklaşıp 1 saat sonra şarj taktimda şarj olmuyor tekrar kapatip açmam gerekli.mi 9 se beta 11kullaniyorum

**Comment by suat074** [comment]
Lütfen buradan sadece çeviri ile ilgili sorunları bildirin. Temiz bir kurulum yapın, düzelmezse xiaomi.eu forumunda bug bölümüne konu açıp bildirin.
