### ISSUE TITLE
KAMERA'DAN GALERİYE GEÇMİYOR(MI 9)

### ISSUE THREAD

**Issue by shritzen** [suat074/MA-XML-11-TURKISH#16]
lütfen düzeltin şu sorunu bıkkınlık getirdi artık

**Comment by rabilgic** [comment]
hangi sürüm?

**Comment by shritzen** [comment]
mi 9 global rom 11.0.6.0 (QFAEUXM)

rabilgic <notifications@github.com>, 21 Ara 2019 Cmt, 08:43 tarihinde şunu
yazdı:

**Comment by shritzen** [comment]
dil türkçe iken geçmiyor bir de. dili ing falan yaptığımızda tıkır tıkır çalışıyor

**Comment by rabilgic** [comment]
Evet hocam da burası xiaomi.eu custom rom türkçe stringlerin bulunduğu proje alanı :) ayrıca xiaomi sorunu haftalık romlarda çözdü yakında global roma güncelleme ile düşer.

**Comment by shritzen** [comment]
bundan önce eu rom kullanıyordum onda da aynı sıkıntı vardı en azından
ulaşsın bir yerlere :d

rabilgic <notifications@github.com>, 26 Ara 2019 Per, 14:04 tarihinde şunu
yazdı:

**Comment by rabilgic** [comment]
bir süre önce loglarla videolarla ulaştırdık hocam :D
