### ISSUE TITLE
Ayarlar Bölümünde Çeviri Hatası

### ISSUE THREAD

**Issue by serkansarikaya** [suat074/MA-XML-11-TURKISH#19]
Mi 9 T Pro'da Ayarlar > Ana Ekran Ayarlarında "-1 ekran" şeklinde yanlış bir çeviri var.

**Comment by suat074** [comment]
Merhaba hocam, cihaz dilini İngilizce yapıp bakar mısınız orijinal çeviride ne yazıyor?
