### ISSUE TITLE
MI8 LITE MESSAGES APP IS NOT WORKING

### ISSUE THREAD

**Issue by rate61** [suat074/MA-XML-11-TURKISH#2]
![Screenshot_2019-10-11-08-24-09-177_com miui home](https://user-images.githubusercontent.com/13119928/66626806-49937100-ec02-11e9-8725-6ab3272a1f2b.jpg)
![Screenshot_2019-10-11-08-29-20-517_com miui bugreport](https://user-images.githubusercontent.com/13119928/66626807-49937100-ec02-11e9-9230-b4189ae2f868.jpg)

This app give error. This app so important for me.

**Comment by ingbrzy** [comment]
not a translation issue
