### ISSUE TITLE
ÇEVİRİ HATASI

### ISSUE THREAD

**Issue by rate61** [suat074/MA-XML-11-TURKISH#20]
Uygulama Bilgisi>Uygulama Davranışı bölümünde hata var en sondaki butonun altındaki yazı galiba çince.

![12](https://user-images.githubusercontent.com/13119928/76443085-f1d87c00-63d2-11ea-9c04-977641ac8694.jpeg)
![13](https://user-images.githubusercontent.com/13119928/76443088-f309a900-63d2-11ea-9bee-d2b8ba010465.jpeg)

Dili ingilizce yapıp ne yazdığına bakmak istedim ama yine çince.

**Comment by suatsari** [comment]
Çince olan satırların İngilizce karşılıkları yayınlandığı zaman çevirip repoya ekleniyor hocam.
