### ISSUE TITLE
Mİ9 SE SES HATASI

### ISSUE THREAD

**Issue by zidan47** [suat074/MA-XML-11-TURKISH#21]
GELEN YADA GİDEN ARAMALARDA KARŞIDAN GELEN KİŞİNİN SESİ İLK 10 SANİYEDEN SONRA GICIRTILI OLUYOR VE HİÇ BİR ŞEY ANLAYAMIYORSUN SESİNDEN. O ESNADA TELEFONUN  AHİZE TUŞUNA BASIP TEKRAR KONUŞMAYA BAŞLADIĞINDA SES DÜZELİYOR. MİUİ 11 GELİŞTİRİCİ VERSİYONLARIN TÜMÜNDE AYNI.

**Comment by suatsari** [comment]
Ben sadece çeviri yapıyorum hocam. EU sitesinde haftalık geliştirici romların olduğu konuya yazabilirsiniz. Ama eğer sorun resmi yazılım ile alakalı ise onlara bir şey yapamazlar. O zaman resmi forumdan geri bildirim yapmanız gerekir.

**Comment by zidan47** [comment]
Teşekkürler Suat hocam.

25 Mar 2020 Çar 02:23 tarihinde suatsari <notifications@github.com> şunu
yazdı:
