### ISSUE TITLE
Mi 9t Eu beta 20.3.19 hatalari

### ISSUE THREAD

**Issue by clb131** [suat074/MA-XML-11-TURKISH#22]
![Screenshot_2020-03-21-02-54-35-086_com alibaba aliexpresshd](https://user-images.githubusercontent.com/62451753/77214484-712b2580-6b20-11ea-8965-f54351267567.jpg)
Mi 9t olan cihazımda k20 rom kurulu yeni güncelleme ile sürekli güvenlik uygulaması tarafından 1 dakika da 1 whatsapp kişilerinize erişti pubg mikrafon kullanılıyor gibi bildirimler geliyor siliyorum 15 sn sonra tekrar geliyor . Parmak izini okutup açtığımda kilid ekranında ki saat cihaz açıldıktan sonra arka planda duvar kağıdın da bir süre kalıp kayboluyor . Menü arası geçişler yavaşladı . Müzik uygulamasında ileri sardığımda müzik tekrar baştan başlıyor . Güvenlik yaması Mart ayına güncellenmesine rağmen şubat gözüküyor .

**Comment by suatsari** [comment]
Ben sadece çeviri yapıyorum hocam. Rom ile ilgili sorunlarınızı eu formundan yapabilirsiniz. Ama o devamlı çıkan bildirim resmi yazılım ile alakalı. 'Uygulama davranışı' ile ilgili yeni bir özellik ve şuan için henüz tam oturtulamadı. Gelecek sürümde inşallah daha kararlı olacaktır.
