### ISSUE TITLE
MI 8 SE MODEM

### ISSUE THREAD

**Issue by bedirdurak** [suat074/MA-XML-11-TURKISH#24]
mi 8 se icin yeni modem dosyasina ihtiyacimiz var artik. yakinlik sensorleri calismiyor, portre modunda yesil ekran aliyoruz, son guncelleme sonrasinda ise sebeke hic calismiyor, wowifi kullanamiyoruz.

**Comment by suatsari** [comment]
Ben sadece çeviri yapıyorum hocam. Rom ile ilgili sorunları Eu forumundan bildirin lütfen.
