### ISSUE TITLE
Mİ9T PRO Xiaomi.eu MIUI 11 stabil rom hataları

### ISSUE THREAD

**Issue by performans1** [suat074/MA-XML-11-TURKISH#4]
merhaba 
türkçe dilde telefonu yeniden başlattığımızda  ,telefon bootloop a düşüyor. diğer bir hata ise kamera uygulamasından resimler görüntülenemiyor. 

güzel çalışmalar dilerim

**Comment by ingbrzy** [comment]
can not be fixed without log
