### ISSUE TITLE
Xiaomi mi 9 türkçe dilde başlama sorunu.

### ISSUE THREAD

**Issue by macir33** [suat074/MA-XML-11-TURKISH#6]
Telefon miui 11 e güncelledikten sonra türkçe açılmıyor loop a giriyor. sürekli resetliyor kendisini.Açılsa bile ilk kurulumda açılıyor ve yeniden başlatınca loop a giriyor tekrar. Ama ingilizce kurulum yapınca herhangi bir sorun yok.

**Comment by ingbrzy** [comment]
can not be solved without logcat
