### ISSUE TITLE
Mi 9 Lite Çift Kamera sorunu, ÜÇLÜ KAMERA olması gereken...

### ISSUE THREAD

**Issue by MaDMaxiBo** [suat074/MA-XML-11-TURKISH#7]
mi 9 lite Türkçe kullanınca Çift kamera yazıyor fotoğraf etiketlerinde, ingilizcesinde Triple yani Üçlü kamera normalde. v11-9.10.31 haftalık rom bahsettiğim. miui 11 de oldu bu sorun

**Comment by ingbrzy** [comment]
fixed for 9.11.28
