### ISSUE TITLE
Mi9 Pro 5G

### ISSUE THREAD

**Issue by enderaltin** [suat074/MA-XML-11-TURKISH#8]
Mi9 Pro 5G  (EU Rom 9.10.31  and EU Rom  9.11.7)
The camera continues to stop.

**Comment by rabilgic** [comment]
Loglar ile birlikte xiaomi.eu forumu bug sekmesinde konu açmalısınız.

**Comment by enderaltin** [comment]
9.11.14 Download link ?

**Comment by suat074** [comment]
@enderaltin lütfen eu forumunu takip edin.
DELAYED DEVICES:
raphael, polaris, ursa, equuelus, pyxis, davinci, crux, cepheus

**Comment by enderaltin** [comment]
teşekkürler suat hocam,  bu hafta kamera sorununu düzelttik  yayınlayacağız dediler.. şimdide ertelenmiş  1 hafta daha kamerasız telefon kullanmak sıkıntı ?

**Comment by suat074** [comment]
Bazen bir veya iki gün sonra yayınlanıyor. Takip edin hocam

**Comment by ingbrzy** [comment]
not a translation issue
