### ISSUE TITLE
Camera Portrait mode does not work.

### ISSUE THREAD

**Issue by kugy28** [suat074/MA-XML-11-TURKISH#9]
Mi8 SE
Camera Portrait mode does not work.

**Comment by rabilgic** [comment]
Hocam ingilizce kasmanıza gerek yok.. Proje adından da anlaşılacağı üzere burası çeviri hatalarının bildirileceği alan. Lütfen rom ile ilgili problemlerinizi xiaomi.eu forumun bug kısmına konu olarak açınız.

**Comment by ingbrzy** [comment]
not a translation issue
